---
title: "Nuevas tecnologías y evasión de impuestos: La recepción de facturas electrónicas en Uruguay"
author: 
  - name: "Guillermo Sánchez Laguardia"
    orcid: 0000-0002-7511-6062
lang: es
format: beamer
editor: visual
bibliography: references.bib
execute: 
  echo: false
  warning: false
callout-icon: false 
---

## Introduction

- Taxation is key in developing state capacities and providing public goods.
- Increasing tax revenue is a central goal of low- and middle-income countries. 
- New technologies offer promising avenues for improving tax compliance (and with it, tax revenue), possibly at lower costs than ever before.

::: {.callout-note}

### This dissertation

I quantify the spillover effects of electronic invoicing in firm tax compliance, using data from the implementation of e-invocing in Uruguay.

:::

## Research Question

- Electronic invoicing has been implemented in many developed and developing countries, including 10 countries in LAC.
- Few impact evaluations, no evaluation of spillover effects, potentially very large. Studying the e-invoice reception approximates downstream spillover effects.

::: {.callout-note} 

### Research question

How does the **reception** of electronic invoices affect tax compliance in firms?

:::

## Setting

- Uruguay is a middle-high income country in Latin America. VAT is a high percentage 
- Electronic invoicing involves creating a digital document of every transaction in treated firms. B2B transactions identify both seller and buyer.

## Data

- I combine several administrative datasets on uruguayan firms between 2009–2016.
  - **E-invoicing records.** Identifing treated firms and time of treatment.
  - **VAT affidavits.** Main outcomes: input VAT, output VAT, VAT liability.
  - **CIT affidavits.** For covariates and auxiliary firm information.

::: {.callout-note}

### Main sample

Small firms that declare input and output VAT. 

:::

## Method

- Event study methodology based on @callawayDifferenceinDifferencesMultipleTime2021.
- Treatment: Year in which firms first recieve an e-invoice.

## Results

## References

::: {#refs}
:::
