project:
  type: book
  output-dir: "../../out/paper"

book:
  title: "Nuevas tecnologías y evasión de impuestos"
  subtitle: "La recepción de facturas electrónicas en Uruguay"
  author: 
  - name: "Guillermo Sánchez Laguardia"
    orcid: 0000-0002-7511-6062
    affiliations:
      - name: "Universidad de la República"
        department: "Facultad de Ciencias Económicas y Adminstración"
  date: "2024-01"
  chapters:
    - index.qmd
    - intro.qmd
    - context.qmd
    - lit_review.qmd
    - hypotheses.qmd
    - method.qmd
    - data.qmd
    - results.qmd
    - closing_remarks.qmd
    - references.qmd
  # appendices:
  #   - appendix_analysis.qmd
  #   - appendix_data.qmd

bibliography: references.bib

lang: es

toc: true

code-fold: true
execute: 
  echo: false
  warning: false

format:
  # html:
  #   theme: simplex
  #   fontsize: 1.2em
  #   linestretch: 1.7
  #   mainfont: Helvetica Neue, Helvetica, Arial, sans
  #   monofont: Cascadia Mono, Menlo, Consolas, Courier New, Courier
  #   backgroundcolor: "white"
  #   fontcolor: "black"
  #   knitr:
  #     opts_chunk:
  #       dev: "ragg_png"
  pdf:
    documentclass: scrreprt
    papersize: a4
    geometry:
      - inner=2.5cm
      - outer=2.5cm
      - top=2.5cm
      - bottom=3cm
      - headsep=22pt
      - headheight=11pt
      - footskip=33pt
      - ignorehead
      - ignorefoot
      - heightrounded
    fig-cap-location: top
    template-partials:
      - before-body.tex
    include-in-header:
      - file: packages.tex
