# Fuentes de datos

## Declaraciones juradas de las empresas

Las empresas tienen que presentar un conjunto de declaraciones juradas periódicamente, informando a la autoridad tributaria sobre distintos aspectos de sus operaciones. En este trabajo utilizamos los siguientes formularios:

> - *Formulario 2148.* Declaración de IRAE, ICOSA e Impuesto al Patrimonio para contribuyentes NO CEDE (para períodos mayores o iguales a 10/2020 deben utilizar el formulario 1050 incluido en PADI).
> - *Formulario 2149.* Declaración de IRAE, ICOSA e Impuesto al Patrimonio para contribuyentes CEDE.
> - *Formulario 2176.* Declaración de IVA, Responsables, Anticipos de IRAE, Impuesto al Patrimonio e ICOSA, para Grandes contribuyentes y Contribuyentes CEDE.
> - *Formulario 2178.* Declaración de IVA, Anticipos de IRAE, Impuesto al Patrimonio e ICOSA para contribuyentes NO CEDE.

## Contribuyentes CEDE y NO CEDE

La DGI clasifica dos grandes tipos de contribuyentes, un grupo de empresas sujeto a un "Control Especial de Empresas" (CEDE) y un grupo no sujeto a ese control adicional (no CEDE). La integración de uno u otro grupo es una decisión administrativa de la DGI, con criterios privados. En general las empresas CEDE se caracterizan por tener niveles elevados de facturación, pertenecer a algún sector de actividad particular, entre otras. El control adicional al que están sujetas se traduce en una mayor frecuencia de presentación de información, a la vez que actúan como agentes de retención de impuestos de sus socios comerciales. Las empresas NO CEDE suelen ser empresas de menor porte y se les requiere presentar menos formularios, con menor frecuencia.