# Comentarios finales {#sec-closing-remarks}

En este trabajo busqué cuantificar el efecto de la recepción de e-facturas sobre el cumplimiento tributario de las firmas en Uruguay en los primeros años de aplicación de la política. Apliqué dos estrategias de estimación de diferencias en diferencias centrándome en una muestra de empresas pequeñas y no encontré ningún efecto estadísticamente significativo sobre el IVA compras, IVA ventas ni IVA adeudado declarado por las empresas de la muestra. Por otra parte, si encuentro un efecto leve en el margen extensivo: la probabilidad de que las empresas receptoras declaren IVA compras e IVA ventas aumenta 1-2%. Utilizando un estrategia de variable instrumental, que me permitió incorporar un mayor número de empresas al análisis, encontré una reducción tenue pero estadísticamente significativa del IVA compras reportado por las empresas.

A grandes rasgos, los resultados son coherentes con las hipótesis planteadas en la [Sección @sec-hypotheses]. En el período de análisis, la política no habría generado suficiente información sobre las empresas receptoras como para poder reducir en gran medida la sobre-declaración de costos. Detectar un efecto tan pequeño presenta un desafío para los datos y métodos utilizados. Por otro lado, los efectos que si logro encontrar coinciden en signo con lo esperado.

La ausencia de efecto –o su reducida magnitud– debería entenderse como un resultado altamente local y parcial. La implementación de la e-facturación alcanzó a todas las empresas recién en 2023, con lo cual la evaluación realizada en este estudio –hasta el año 2015– puede interpretarse como un efecto de corto plazo. Evaluaciones de políticas similares en otros países sugieren que los efectos en el mediano y largo plazo pueden ser sustancialmente mayores [@bellonDigitalizationImproveTax2022; @fanDynamicEffectsComputerizing2023]. En el caso uruguayo, es necesario contar con datos más recientes de la actividad de las empresas para evaluar la e-facturación de forma integral.

Hay dos puntos específicos que sería interesante explorar a futuro. En primer lugar, una limitación de este trabajo es no haber logrado estudiar los efectos de la recepción de e-facturas en el margen intensivo de las declaraciones. Estudios posteriores que incorporen un diseño diferente y/o un mayor número de observaciones podrían superar este problema.  En segundo lugar, el efecto encontrado sobre IVA ventas sugiere que la recepción de e-facturas puede impactar la declaración de variables sobre las cuales la política no está aportando información nueva. Falta explorar cual es el alcance de este efecto. En particular, la política podría tener impacto sobre la declaración de otros impuestos como el IRAE, a pesar de que dichos impuestos no aparezcan directamente en las e-facturas. Cuantificar el impacto de la política sobre otros impuestos, tanto para la recepción como para la emisión de e-facturas, es una pregunta aún no abordada en la literatura.