# Contexto {#sec-context}

```{r data-context}
library(groundhog)
pkgs <- c("data.table", "magrittr", "ggplot2", "patchwork", "fst", "lubridate")
date <- "2024-01-15"
groundhog.library(pkgs, date)

ROOT <- ""
if (grepl("src/paper", getwd())) ROOT <- "../../"

source(paste0(ROOT, "src/lib/theme_set.R"))

samples <- read_fst(paste0(ROOT, "out/data/samples.fst"), as.data.table = TRUE)
dts <-
  read_fst(paste0(ROOT, "out/data/firms_static.fst"), as.data.table = TRUE) %>%
  .[samples[(activeBusinessAnyT)], on = "fid"]
```

## Impuestos a las empresas en Uruguay

Las empresas uruguayas están sujetas a un impuesto a las ganancias empresariales (Impuesto a las Rentas de las Actividades Económicas, IRAE) y un impuesto al valor agregado (IVA), entre otros gravámenes. El IRAE grava las rentas empresariales a una tasa de 25%. El IVA tiene una tasa básica de 22% y una tasa reducida de 10% aplicada a productos de primera necesidad. Además de IVA e IRAE, hay un Impuesto al Patrimonio (IPAT) de las empresas de 1,5% y otra serie de impuestos específicos a ciertas características de la empresa y/o su producción.[^other-taxes]

[^other-taxes]: El Impuesto de Control a las Sociedades Anónimas (ICOSA) es un impuesto de suma fija (\$14.000 al cierre del ejercicio en 2016) aplicado únicamente a las empresas constituídas como Sociedades Anónimas. El Impuesto a la Enajenación de Bienes Agropecuarios (IMEBA) grava por hasta 2,5% del valor de las ventas de negocios agropecuarios de pequeña escala. El Impuesto Específico Interno (IMESI) grava consumos específicos a tasas variadas, fijadas por distintas leyes y decretos. Las empresas extranjeras están sujetas al Impuesto a la Renta de No Residentes (IRNR) en lugar del IRAE. No están contempladas en este análisis. Por otro lado, las personas físicas están sujetas al Impuesto a la Renta de las Personas Físicas (IRPF), un impuesto dual que grava los ingresos de capital a tasas fijas (IRPF categoría I) y los ingresos laborales a partir de un esquema de tasas progresivas (IRPF cat. II).

Las empresas pequeñas y medianas cuentan con regímenes especiales de declaración de impuestos. Las empresas más pequeñas –con ingresos anuales menores a 305.000 Unidades Indexadas (UI, aprox. \$1.000.000 en 2016)– están exoneradas de pagar IRAE. Además pagan IVA Mínimo, un monto mensual fijo no dependiente de su facturación ni de sus compras; en 2016 era \$2.950. Las empresas exoneradas no deben presentar declaraciones juradas de IRAE ni IVA, pero sí deben hacer una declaración anual de su patrimonio para el pago de IPAT.

Las empresas pequeñas que facturan más de 305.000 UI no están exoneradas de ningún impuesto y deben presentar declaraciones juradas de IRAE, IVA e IPAT todos los años. No obstante, están amparadas por un régimen preferencial de IRAE "ficto". Bajo el régimen ficto, las empresas declaran sus ingresos anuales y se les imputa una renta ficta, que luego queda gravada por IRAE al 25%. La tasa de ganancia ficta varía por tramos de facturación para incentivar a las empresas a desarrollar sistemas de contabilidad suficiente a medida incrementan su producción. En la práctica, el régimen ficto opera como un impuesto a la facturación de las empresas bajo un esquema de tasas progresivas.[^fict]

[^fict]:  Para facturaciones menores a 2 millones de UI, se asume una tasa de beneficio de 13.2%; entre 2 y 3 millones de UI la tasa es de 36%; y para facturaciones mayores a 3 millones de UI la tasa ficta asciende a 48%. Son equivalentes a un impuesto a la facturación a tasas de 3.3%, 9%, y 12%.    La discontinuidad en las tasas es pronunciada y logra incentivar a las empresas a presentar declaraciones reales de su actividad: solo 5% de las empresas que presentan declaraciones fictas reportan una facturación mayor a 2 millones de UI.

En el otro extremo, hay un subconjunto de empresas monitoreadas de forma más exhaustiva por la unidad de Control Especial de Empresas de la DGI (en más, empresas CEDE). La DGI decide qué empresas estarán en la órbita de dicha unidad siguiendo criterios adiminstrativos privados; en general suelen ser empresas con niveles altos de facturación y/o insertas en sectores de actividad con mayor riesgo de evasión. Las empresas CEDE presentan declaraciones juradas mensuales de IVA y semestrales de IRAE. El resto de las empresas no-CEDE (que no se amparen en ninguno de los regímenes especiales mencionados) presentan declaraciones juradas de IVA e IRAE con frecuencia anual.

La Dirección General Impositiva (DGI) de Uruguay recauda impuestos por cerca de 19% del PIB (2019). El IVA representa 46% de la recaudación y el IRAE 14%. Las únicas estimaciones de evasión en empresas para Uruguay refieren al IVA. La @direcciongeneralimpositivaEstimacionEvasionImpuesto2019 estimaba que la tasa de evasión de IVA en 2012 era cercana al 13%. Es una tasa de evasión baja para la región: @gomezsabainiTaxStructureTax2012 estimaban que la brecha de cumplimiento del IVA en América Latina era en promedio 25,9% en 2006, variando desde 11,0% en Chile hasta 38,1% en Nicaragua. A su vez, la evasión estimada en Uruguay es comparable a las estimaciones para algunos países desarrollados. Por ejemplo, la brecha de cumplimiento del IVA en la Unión Europea era de 11% en 2018 con amplia variación entre países. Las brechas más bajas se encontraron en Suecia (0,7%), Croacia (3,5%) y Finlandia (3,6%), y las más altas en Rumania (33,8%), Grecia (30,1%) y Lituania (25,9%) [@europeancommissiondgtaxudStudyReportsVAT2020].

## Facturación electrónica

La facturación electrónica involucra la emisión de comprobantes digitales que documentan las operaciones comerciales de una empresa. Desde la perspectiva de la administración tributaria, la tecnología permite un acceso a información tributaria prácticamente en tiempo real, lo cual permite hacer mejores proyecciones de recaudación, comprender mejor la dinámica de la actividad de las empresas, y automatizar procesos de control y fiscalización. La política también tiene beneficios para los contribuyentes, en tanto reduce los costos de cumplimiento y puede mejorar la eficiencia a partir de la reducción de costos operativos y a las ganancias de potenciales procesos de automatización e integración entre empresas [@barreixFacturaElectronicaAmerica2018].

La facturación electrónica en Uruguay comienza a diseñarse en el año 2011. Tras una etapa previa de diseño del sistema en conjunto con empresas, la aprobación de normativa específica, y la ejecución de un plan piloto con 30 empresas, comienzan a operar los primeros emisores en 2012. Entre 2012 y 2014, se ofrecen reducciones fiscales importantes para incentivar a las empresas a incorporarse voluntariamente al sistema. En este período, también se obliga a ingresar a grandes contribuyentes, empresas sujetas a control especial por parte de la DGI[^cede], y empresas con giro free shop. Luego, en 2015 se establece un calendario de ingreso obligatorio vinculado al nivel de ventas reportado por las empresas [@canalesUruguayPerfilFactura2018].

[^cede]: También conocidas como CEDE, Control Especial de Empresas.

La política contempla la emisión de varios tipos de comprobantes electrónicos, documentando operaciones entre contribuyentes (e-facturas) y con consumidores finales (e-tickets). A su vez, hay documentos específicos para el envío de mercadería (e-remito), la retención de impuestos (e-resguardo), y para operaciones de exportación (e-factura de exportación, e-remito de exportación). Los comprobantes contienen información exhaustiva de cada operación, dentro de la cual aparecen tributos (IVA, IMESI) y retenciones (IRAE, IRPF) correspondientes. La empresa emisora debe enviar el comprobante electrónico a la DGI y al receptor electrónico antes de concretar la operación. Además, debe crear y remitir un reporte diario con información consolidada de todos los comprobantes emitidos en el día, desagregado por tipo de comprobante y por sucursal [@direcciongeneralimpositivaFormatoCFE2023; @direcciongeneralimpositivaFormatoReporteDiario2023; @canalesUruguayPerfilFactura2018].

Dispongo de información del sistema de facturación electrónica desde el comienzo de su implementación hasta noviembre de 2016. En dicho período, solamente las empresas con más de 30 millones de Unidades Indexadas (en adelante, UI) de facturación anual[^context-2] –y un grupo reducido de grandes contribuyentes– habían sido mandatados a emitir comprobantes electrónicos. Las demás empresas serían obligadas a emitir gradualmente, de acuerdo a un calendario definido por facturación, que mandataba a una nueva cohorte de empresas a emitir e-facturas cada seis meses. La @tbl-policy-adoption-schedule presenta dicho calendario.

[^context-2]: Equivalente en ese momento a 3.3 millones de USD de facturación anual.

El panel (a) de la @fig-adoption muestra como se distribuyó dicha adopción en el tiempo, a partir de los microdatos de DGI (describo los datos en mayor detalle en la [Sección @sec-data]). A noviembre de 2016 habían ingresado `r dts[(emittedAnyT), .N]` empresas al régimen de facturación electrónica, correspondientes a 3% de la muestra. La línea vertical en junio de 2016 marca el inicio de la obligatoriedad de emisión para las empresas con ingresos mayores a 30 millones de UI.

A pesar de tratarse de un número reducido de empresas emisoras, por una combinación de sus amplios volúmenes de facturación y su posicionamiento en la cadena productiva, una proporción sustancial de las empresas uruguayas recibió alguna factura electrónica en relativamente poco tiempo. El panel (b) de la @fig-adoption ilustra como ya desde inicios de 2014 más de la mitad de las empresas uruguayas había recibido alguna e-factura. Como se verá en la [Sección @sec-results], sin embargo, la información generada por la política sobre las compras de las empresas receptoras distaba de ser completa.