# Datos {#sec-data}

```{r data-intext}
library(groundhog)
pkgs <- c("data.table")
date <- "2024-01-15"
groundhog.library(pkgs, "2024-01-15")

ROOT <- ""
if (grepl("src/paper", getwd())) ROOT <- "../../"
awd <- \(x) paste0(ROOT, x)

intext <- fread(awd("out/analysis/intext_refs.csv"))
```

## Fuentes de datos y variables de análisis

Para estudiar el impacto de la recepción de e-facturas combino varias fuentes de microdatos de las empresas uruguayas. En primer lugar, uso información del sistema de facturación electrónica. Dispongo de un resumen mensual de todas las transacciones entre empresas desde la implementación del sistema en enero de 2012 hasta noviembre de 2016. Cada línea resume las transacciones entre una dupla de empresas –emisora y receptora–, registrando el número de operaciones y el valor total de las mismas. La base me permite identificar el mes exacto en que las empresas comienzan a emitir y recibir e-facturas.

Combino esta información con declaraciones juradas de las empresas asociadas al pago de distintos impuestos. La declaración jurada de IVA es la fuente de mis principales variables de resultado. De allí obtengo los reportes de IVA compras, IVA ventas e IVA adeudado por las empresas en un determinado año. La declaración jurada de IRAE e IPAT contiene la información que utilizo para construir mis covariables principales: ingreso anual, nivel de activos, sector de actividad, edad de la empresa y régimen de declaración de impuestos (exonerado/ficto/real).

Por último, también cuento con un registro mensual de pagos de impuestos de las empresas a la DGI. Contiene el pago total por impuestos, desagregado en IVA, IRAE, y un conjunto de otros impuestos de menor recaudación. La mayor parte de mis análisis utilizan datos anuales porque es la frecuencia que tienen casi todas las declaraciones juradas. Para ello colapso los datos de frecuencia mensual –pagos de impuestos y transacciones con comprobantes electrónicos– a frecuencia anual. La @tbl-data resume las fuentes de datos y su período de cobertura.

Me concentro en cuatro resultados de las empresas: IVA compras, IVA ventas, IVA adeudado y pagos de IVA. La forma funcional de las variables dependientes no es trivial.  @chenLogsZerosProblems2023 señalan los peligros de utilizar transformaciones cuasi-logarítmicas definidas en cero –como $\log(Y+1)$ o $\text{arcsinh}(Y)$– de variables dependientes no negativas. Interpretar los efectos de tratamiento estimados usando este tipo de transformaciones como efectos porcentuales es un error, en tanto dependen de la unidad de medida de $Y$. Si el tratamiento tiene un efecto en el margen extensivo, los autores muestran es posible obtener efectos de tratamiento de cualquier magnitud re-escalando $Y$ antes de aplicar la transformación cuasi-logarítimica. Se proponen varias alternativas para la estimación; en este trabajo opto por normalizar las variables de resultado utilizando una covariable pre-tratamiento. La ventaja de esta alternativa es que permite una interpretación de los efectos de tratamiento invariante a la escala. [^non-zero]

Con esto en mente y siguiendo el análisis de @yaganCapitalTaxReform2015, deflacto todas las variables de resultado a pesos de 2016 y las normalizo por el ingreso anual promedio de la empresa entre 2009 y 2010 deflactado – antes de que se implementara la e-facturación–. Además, incorporo un conjunto de controles en todas mis estimaciones: cuartiles de activos pre-tratamiento, cuartiles de edad de las empresas y 88 divisiones de sectores de actividad en base al código CIIU a dos dígitos.

[^non-zero]: La @fig-share-zero muestra la proporción de empresas que reportan cero IVA ventas, IVA compras, IVA adeudado y pagos de IVA por año. En todos los casos la proporción se sitúa entre 10% y 20%, una fracción no trivial.

### Definición del tratamiento

Tomo el **año donde la empresa recibe su primera factura electrónica** como el inicio del tratamiento. Exploto la variación en el año del tratamiento para estimar el efecto de la recepción de e-facturas. Defino el tratamiento de forma binaria y absorbente. El tratamiento es binario en tanto no considero distintas intensidades de recepción de e-facturas. El tratamiento es absorbente en tanto –en la mayoría de los casos– una vez que la empresa recibe su primer e-factura, las sigue recibiendo todos los años hasta el final del período.

## Muestra principal

Mi muestra principal es un panel balanceado de empresas que pagan impuesto a las ganancias por régimen ficto (ver @sec-context) todos los años entre 2009 y 2016. Son empresas con ingresos anuales mayores a 305.000 UI que presentan declaraciones juradas de IVA, IRAE e IPAT todos los años. Uso un panel balanceado para evitar problemas de composición por entradas y salidas durante el período.

Me centro en las empresas que presentan declaraciones fictas de ingresos por dos razones. La primera es su *potencial evasor*. (Algo de forma de presentar impuestos (+++)). Además, se trata de empresas menor porte y varios estudios teóricos [@klevenWhyCanModern2016] y empíricos [@pomeranzNoTaxationInformation2015; @adhikariSmallBusinessTax2021; @bellonDigitalizationImproveTax2022] sugieren que evaden en mayor medida que empresas más grandes. La segunda razón es que sería deseable que las empresas no influyeran en la decisión de sus proveedores de comenzar a emitir e-facturas. El reducido tamaño de las empresas analizadas y su poca importancia como jugadores individuales vuelve plausible que el momento exacto en que las empresas empiezan a recibir e-facturas sea (relativamente) exógeno.

Impongo dos restricciones adicionales a la muestra. Primero, excluyo a las empresas en las que el tratamiento no se comporta de forma absorbente. Es decir, descarto a las empresas que reciben e-facturas de forma intermitente, con años que reciben y años que no. Se trata de menos de 1% de las empresas del panel balanceado e incluirlas dificultaría la interpretación de los resultados de las estimaciones.[^alt-method]. Segundo, excluyo a las empresas que no reciben e-facturas en el período. Es un grupo reducido (13% de la muestra) con características muy distintas al resto de las empresas consideradas (ver @sec-results) y @callawayDifferenceinDifferencesMultipleTime2021 sugieren la exclusión de la muestra en casos como este.

[^alt-method]: Estrictamente, el método que utilizo en mis estimaciones solo peemite tratamientos binarios y absorbentes [@callawayDifferenceinDifferencesMultipleTime2021; ver @sec-method]. Hay métodos alternativos que contemplan tratamientos no absorbentes [ver por ejemplo @dechaisemartinDifferenceinDifferencesEstimatorsIntertemporal2022].

Hay `r intext[cmd == "dts[(inSample3), .N]", out]` empresas en la muestra final. La @tbl-sample-summary presenta sus principales características. Se trata de empresas relativamente pequeñas, que en 2009–2010 presentaban facturación anual promedio de \$`r intext[cmd == "(dty[(inSample3), fmean(Scaler1)] / 1e6) |> round(digits = 1)", out]` millones. Se observa que `r intext[cmd == "dty[(inSample3), fmean(neverTreated)] |> round(digits = 1)", out]`% de las empresas en la muestra recibe alguna e-factura entre 2012 y 2016. En contraste, solo `r intext[cmd == "dty[(inSample3), fmean(emittedAnyT)] |> round(digits = 1)", out]`% empresas emiten e-facturas. La empresa mediana en la muestra reportaba \$0,61 de compras deducibles por peso de ingreso rezagado, \$0,30 de IVA ventas, \$0.14 de IVA compras y \$0.03 en pagos de IVA.

En la muestra final solo `r intext[cmd == "round(100 * dts[(inSample3), fmean(neverTreated)], digits = 1)", out]`% de las empresas llega a 2016 sin haber recibido algún comprobante electrónico. La @fig-adoption-inSample presenta la función de distribución acumulada de la primera recepción para el universo de empresas y para la muestra seleccionada. La adopción se extiende más rápido en la muestra que en el universo de empresas: a principios de 2015 el 80% de la empresas de la muestra había recibido alguna e-factura.