# Discusión {#sec-discussion}

El sobre-reporte de costos es una de las principales formas de evasión de IVA [@waseemInformationAsymmetricIncentives2019; @waseemOverclaimedRefundsUndeclared2023; @fanDynamicEffectsComputerizing2023]. La recepción de e-facturas crea una base de datos sobre los costos de las empresas que la autoridad tributaria puede utilizar para verificar declaraciones juradas y –potencialmente– detectar instancias de sobre-reporte de costos. Este era el principal efecto que esperaba encontrar de la política, pero como detallé en la [Sección @sec-results], no encuentro ningún efecto significativo. Hay al menos dos factores que pueden explicar esto.

Por un lado, la ausencia de efecto puede deberse a la implementación incompleta de la política en el momento del estudio. La autoridad tributaria puede tener dificultades para detectar inconsistencias de costos cuando la digitalización de las transacciones entre empresas es parcial. Como detallé en la [Sección @sec-results-rollout], al final del período para el 75% de las empresas receptoras los costos capturados en e-facturas representaban menos del 50% de los costos reportados. En este contexto, las empresas pueden alegar que sus (sobre)costos provienen de transacciones con empresas que no emiten comprobantes digitales.

@carrilloDodgingTaxmanFirm2017 destacan una asimetría en la capacidad de la información externa para afectar las declaraciones juradas de impuestos. En general, las fuentes externas operan como un piso para las declaraciones de las empresas. Cuando la información refiere a las ventas, ese piso puede llevar a una reducción del sub-reporte de ingreso. No obstante, en el caso de los costos –a no ser que la fuente externa tenga una cobertura completa– las empresas pueden sobre-reportar por encima de ese piso y reducir su deuda tributaria. El resultado va en línea con las hipótesis (H1) y (H2) planteadas en la [Sección @sec-hypotheses].

Por otra parte, pueden haber problemas con el diseño seleccionado. La muestra que utilizo en mis estimaciones corresponde al primer quintil de facturación de las empresas presentan declaraciones juradas no simplificadas en el panel balanceado 2009–2015. Es una muestra reducida pero, como detallé en la descripción de la muestra en la [Sección @sec-data], las empresas más grandes podrían afectar la decisión de sus proveedores de adoptar la facturación electrónica y, por lo tanto, la relativa aleatoriedad del momento en que comienzan a recibir e-facturas.

En el @sec-appendix-iv pruebo una metodología alternativa, estimando los efectos con una estrategia de variables instrumentales. Encuentro que la recepción de e-facturas reduce de forma estadísticamente significativa el IVA compras reportado, pero el efecto es económicamente insignificante. Por otra parte, no encuentro efectos sobre IVA ventas ni IVA adeudado. En otras palabras, aún con una metodología alternativa y con otra muestra de empresas, encuentro un efecto muy moderado de la recepción de e-facturas sobre el cumplimiento tributario. Este ejercicio reafirma que la implementación incompleta de la política al momento de esta evaluación es un factor central para evaluar la reducida o nula magnitud de los efectos encontrados.

Mi última pregunta de investigación refería a potenciales heterogeneidades en el efecto de la política de acuerdo al tamaño de la empresa, la relevancia del consumo final en sus ventas y su proporción de insumos importados. En la [Sección @sec-hypotheses] planteé que esperaba encontrar efectos de mayor magnitud entre (H6) empresas más pequeñas, (H7) sectores con mayor proporción de la producción destinada al consumo final de los hogares, y (H8) sectores con menor utilización de insumos importados. No encuentro efectos estadísticamente diferentes a cero en ninguno de los cortes que estudio; ni puedo afirmar que los coeficientes estimados para cada subgrupo sean estadísticamente distintos entre sí. Tampoco puedo descartar la ausencia de efectos heterogéneos con la estrategia de variables instrumentales. Vale aclarar, nuevamente, que estos resultados pueden deberse a una falta de poder para detectar efectos que, como se observó, tienen una magnitud muy reducida en el período analizado.
