\pagenumbering{arabic}
\setcounter{page}{1}

# Introduction {#sec-intro}

Developing countries face significant challenges in collecting tax revenue, which constrains their ability to implement policies and provide public goods. Economic growth alone does not appear sufficient to increase government revenue as a share of GDP. Instead, governments need to make targeted investments to strengthen their capacity for revenue collection [@okunogbeHowCanLowerIncome2024]. The adoption of new technologies in tax administration offers a promising avenue for achieving this goal, as these tools can enhance the three core functions of tax administration: identifying taxpayers, calculating tax liabilities, and collecting payments in a timely manner [@okunogbeBecomingLegibleState2023].

One such technology is electronic invoicing (e-invoicing), which involves issuing digital documents registering firms' transactions. These documents are automatically transmitted to customers involved in the transaction and to the tax authority. Once widely adopted, e-invoicing generates detailed information that allows tax authorities to cross-check firms' tax returns against accurate data on their commercial activities, thereby reducing opportunities for evasion [@barreixFacturaElectronicaAmerica2018]. Both developed and developing countries have adopted e-invoicing systems, including ten countries in Latin America and the Caribbean [@barreixFacturaElectronicaAmerica2018].

Several studies have shown that e-invoicing is effective in curbing tax non-compliance among firms issuing e-invoices [@bellonDigitalizationImproveTax2022; @fanDynamicEffectsComputerizing2023]. For example, @bergoloFacturaElectronicaCumplimiento2018 report a 3.7% increase in Value Added Tax (VAT) payments in Uruguay within six months of firms adopting e-invoicing. However, we know very little about how this policy affects the firms that *receive* e-invoices. This is an important gap because it is one of the main channels through which the policy may affect firms that have not yet adopted e-invoice issuance, i.e. spillover effects. To address this gap, I examine the introduction of e-invoicing in Uruguay in 2012, analysing its impact on the tax compliance of firms that receive e-invoices.

Each e-invoice identifies the seller and the buyer involved in a transaction, creating a record of the issuing firm’s _sales_ and the receiving firm’s _purchases_. As mentioned, this aggregate record of transactions can reduce sales under-reporting by issuing firms.But it can also reduce cost over-reporting by receiving firms, operating as a new source of third-party reported information that the tax authority can use to verify tax returns [@carrilloDodgingTaxmanFirm2017; @pomeranzNoTaxationInformation2015; @klevenUnwillingUnableCheat2011]. Specifically, I expect e-invoice reception will reduce cost overreporting, not affect reported revenue and –consequently– increase the tax liability of receiving firms.

To test these hypotheses, I employ a difference-in-differences methodology with staggered treatment adoption, exploiting variation in the dates when firms first receive e-invoices. My analysis uses microdata from value added tax (VAT) returns filed by Uruguayan firms between 2009 and 2016, as well as transaction records from the e-invoicing system. I restrict the sample to relatively small firms, in order to to minimise the probability that these firms influenced their business partners’ decision to adopt e-invoicing.

First, I characterise the rollout of e-invoicing in Uruguay. Between 2012 and 2016, the policy expanded rapidly. The earliest adopters, either due to their high revenues or their position in commercial networks, quickly began transacting with a substantial proportion of Uruguayan firms. By early 2014, 60% of firms had received at least one e-invoice, even though only 100 firms had adopted the system. Nonetheless, during this period, the proportion of recipient firms’ purchases covered by e-invoices remained low. As adoption grew, cthe share of purchases recorded through e-invoices grew exponentially, reaching a median coverage of 27% in 2016.

Then, I study the impact of receiving e-invoices on VAT compliance among recipient firms. I focus on VAT because e-invoices explicitly record this tax, making it the tax most likely to be affected by the policy. My analysis examines three variables reported in tax returns: input VAT, output VAT, and net VAT liability. I find no statistically significant effects on any of these variables for small firms in the sample. This null result remains robust across various specifications, including an alternative estimation method proposed by @callawayDifferenceinDifferencesMultipleTime2021, which addresses limitations in traditional difference-in-differences approaches with staggered treatment adoption [see reviews by @rothWhatTrendingDifferenceindifferences2023 and @dechaisemartinTwowayFixedEffects2023].

This research is framed within several current discussions in the tax compliance literature. I contribute to studies that analyse policy responses to tax evasion [see review by @slemrodTaxComplianceEnforcement2019], particularly those that emphasise the role of third-party-reported information in supporting tax compliance [e.g., @klevenUnwillingUnableCheat2011; @klevenWhyCanModern2016; @pomeranzNoTaxationInformation2015; @carrilloDodgingTaxmanFirm2017]. It is also linked to broader research on the impacts of new technologies in public administration and state capacity building in developing countries [e.g., @guptaDigitalRevolutionsPublic2017; @lewis-faupelCanElectronicProcurement2016; @muralidharanBuildingStateCapacity2016; @banerjeeEgovernanceAccountabilityLeakage2020]. Specifically, I seek to contribute to the literature on the adoption of technology in tax administration [@okunogbeTechnologyTaxationCorruption2022].

Empirical studies have primarily focused on the effects of *issuing* e-invoices on tax compliance and firm outcomes [e.g., @eissaEvaluationElectronicBilling2015; @bellonDigitalizationImproveTax2022; @fanDynamicEffectsComputerizing2023], but none have examined the impact of _receiving_ e-invoices on firms. This is an important gap, considering recent literature highlights the importance of evaluating such indirect effects in policy interventions in order to make comprehensive evaluations [@lopez-luzuriagaComplianceSpilloversTaxes2019]. By analysing e-invoice reception, I aim to approximate *downstream spillover effects* of e-invoicing, i.e. the effect of issuing firms on their buyers.

This thesis is organised as follows. In [Section @sec-lit-review], I review the relevant literature, and in [Section @sec-context], I outline the policy context. I present the hypotheses guiding this analysis in [Section @sec-hypotheses]. In [Sections @sec-data] and [-@sec-method], I describe the data and methodology. I discuss the findings in [Section @sec-results], followed by a discussion in [Section @sec-discussion]. Finally, I conclude in [Section @sec-closing-remarks].
