# Introducción {#sec-intro}

La evasión de impuestos aumenta el costo de la recaudación y administración impositiva, altera la distribución de la carga fiscal [@slemrodTaxAvoidanceEvasion2002], y crea distorsiones tanto en la producción como en las decisiones de consumo [@skinnerEconomicPerspectiveTax1985; @pestieauTaxEvasionOccupational1991]. Puede limitar el desarrollo de las capacidades estatales –en particular, la capacidad de recaudar impuestos– y restringir el desempeño económico de países en desarrollo [@burgessTaxationDevelopment1993; @besleyTaxationDevelopment2013]. A su vez, puede propiciar el diseño de sistemas tributarios que dependan de instrumentos fiscales que, en otro contexto, serían ineficientes [@gordonTaxStructuresDeveloping2009; @bestProductionRevenueEfficiency2015]. En síntesis, la evasión fiscal representa un desafío central para la gestión tributaria, que se agudiza en países en desarrollo.

Una literatura creciente ha enfatizado el rol de la información en el cumplimiento tributario. En particular, se ha destacado la importancia de la información reportada por terceros, es decir, la capacidad de corroborar las declaraciones de impuestos de los contribuyentes con otras fuentes. Incluye, por ejemplo, la posibilidad de verificar declaraciones de ingresos personales contra la nómina salarial de los empleadores [@klevenUnwillingUnableCheat2011; @kumlerEnlistingEmployeesImproving2020], la validación cruzada de operaciones de las empresas con sus socios comerciales [@kopczukPuttingFirmsOptimal2006; @pomeranzNoTaxationInformation2015], con registros bancarios y financieros [@carrilloDodgingTaxmanFirm2017; @slemrodDoesCreditcardInformation2017; @adhikariSmallBusinessTax2021], y con reportes directos de consumidores finales [@naritomiConsumersTaxAuditors2019].  La información reportada por terceros ha sido es un rasgo central de la administración tributaria en los países de altos ingresos y ha sido señalada como uno de los factores que permiten a los gobiernos de esos países cobrar altos impuestos y mantener elevados niveles de cumplimiento tributario [@klevenWhyCanModern2016].

En tiempos recientes, la adopción de tecnologías digitales está transformando radicalmente la operativa de las autoridades tributarias, potenciando su capacidad para administrar, recolectar y procesar información impositiva [@guptaDigitalRevolutionsPublic2017]. En particular, la incorporación de tecnologías ha facilitado la verificación cruzada de amplios contingentes de información provenientes de diversas fuentes, a un costo más reducido que nunca. Una de estas tecnologías es la facturación electrónica: la emisión de comprobantes digitales que registran las transacciones de una empresa, los cuales pueden transmitirse automáticamente a los clientes involucrados en cada transacción y a las autoridades fiscales. Una vez que se adopta de manera generalizada, las autoridades fiscales pueden acceder a información detallada sobre todas las transacciones entre empresas y consumidores, lo que les brinda la capacidad de contrastar las declaraciones de impuestos de las empresas con datos precisos sobre sus operaciones [@barreixFacturaElectronicaAmerica2018]. En otras palabras, al adoptar la facturación electrónica, las autoridades tributarias obtienen una visión más completa de las empresas, lo que potencialmente reduce las oportunidades de evasión fiscal. Además, al simplificar la detección de incumplimientos, la facturación electrónica puede servir como un disuasivo más efectivo contra la evasión fiscal.

Motivados por las potenciales ganancias de eficiencia y efectividad en la fiscalización, varios países desarrollados y en vías de desarrollo han implementado sistemas de facturación electrónica, entre los cuales se cuentan diez países en América Latina y el Caribe [@barreixFacturaElectronicaAmerica2018]. Uruguay comenzó su proceso de adopción de esta política en 2012. Debido a los grandes costos de implementación para la administración tributaria y para las empresas, la reforma fue implementada de forma gradual. @bergoloFacturaElectronicaCumplimiento2018 evalúan la implementación de la factura electrónica en Uruguay. Aplican un diseño de estudio de eventos y encuentran que los pagos y retenciones del Impuesto al Valor Agregado (IVA) aumentan 3,7% en los seis meses posteriores al ingreso al régimen de facturación electrónica.

Adopto una metodología de diferencias en diferencias con adopción escalonada del tratamiento, explotando la variación en las fechas en que las empresas reciben su primer e-factura. Avances recientes en la literatura de diferencias en diferencias han señalado diversos problemas con los métodos tradicionales de estimación, en diseños de adopción escalonada [ver reseñas de @rothWhatTrendingDifferenceindifferences2023; y @dechaisemartinTwowayFixedEffects2023]. Con esto en mente, realizo las estimaciones siguiendo la propuesta de @callawayDifferenceinDifferencesMultipleTime2021, que elude los principales problemas de métodos anteriores. El análisis empírico utiliza microdatos provenientes de pagos y declaraciones de impuestos de las empresas uruguayas entre 2009–2016, y un registro de transacciones del sistema de facturación electrónica.

Centro mi análisis en un subconjunto de empresas de facturación reducida, y que pagan impuestos a las ganancias empresariales en base a su facturación. Es un grupo de empresas con mayor potencial evasor de acuerdo a varios resultados de la literatura [@bestProductionRevenueEfficiency2015; @almuniaRadarEffectsMonitoring2018; @slemrodTaxComplianceEnforcement2019; @bellonDigitalizationImproveTax2022]. Además, por su tamaño reducido, no deberían influenciar la decisión de sus socios comerciales de convertirse en emisores.

En primer lugar, caracterizo la recepción de e-facturas en Uruguay. Estudio la expansión de la política entre 2012 y 2016 y cuantifico la información nueva que logró generar sobre las compras de empresas pequeñas y medianas. Encuentro que las primeras empresas en emitir e-facturas, ya por sus niveles de facturación o posicionamiento en la red productiva, establecen transacciones rápidamente con una proporción sustancial de las empresas uruguayas. Encuentro que para principios de 2014 el 60% de las empresas pequeñas y medianas habían recibido alguna e-factura, momento en el que habían solo 100 empresas emitiendo comprobantes electrónicos. No obstante, en el comienzo de la política la proporción de compras de las empresas receptoras que quedaba registrada en e-facturas era muy reducida. A medida la emisión de e-facturas se expandió, la cobertura de las compras creció exponencialmente, alcanzando una cobertura mediana de 45% en 2016.

En segundo lugar, estudio el impacto de la recepción de e-facturas sobre el cumplimiento tributario de las empresas receptoras. Me concentro en cuatro variables: IVA Compras, IVA Ventas, IVA adeudado y pagos de IVA. Encuentro que las empresas que reciben e-facturas incrementan declaran 8% más IVA Compras y 9% más IVA Ventas dentro de los tres años posteriores a empezar a recibir e-facturas. También encuentro un aumento del IVA adeudado de 11% y de 14% en los pagos de IVA tres años después de la primera recepción.  Por último, investigo heterogeneidades en los efectos de la recepción de e-facturas sobre el cumplimiento tributario. Encuentro que las empresas de menor facturación y ciertos sectores de actividad responden de forma más intensa a la recepción de e-facturas.

Esta tesis se enmarca en varias discusiones actuales de la literatura sobre cumplimiento tributario. En primer lugar, busca dialogar con los trabajos que estudian respuestas a la evasión tributaria desde las políticas públicas [ver reseña de @slemrodTaxComplianceEnforcement2019]. Más específicamente, se vincula con la literatura que destaca la relevancia de la información reportada por terceros para apuntalar el cumplimiento tributario [@klevenUnwillingUnableCheat2011; @klevenWhyCanModern2016; @pomeranzNoTaxationInformation2015; @carrilloDodgingTaxmanFirm2017, entre otros]. En segundo lugar, también se vincula con la literatura que estudia el impacto de las nuevas tecnologías en la administración pública y sus impactos en la construcción de capacidades estatales en países en desarrollo [@guptaDigitalRevolutionsPublic2017; @lewis-faupelCanElectronicProcurement2016; @muralidharanBuildingStateCapacity2016; @banerjeeEgovernanceAccountabilityLeakage2020].En particular, mi tesis busca contribuir a la literatura sobre la adopción de nuevas tecnologías en la administración tributaria [@okunogbeTechnologyTaxationCorruption2022].

Otros estudios empíricos han analizado el impacto de la *emisión* de e-facturas [@eissaEvaluationElectronicBilling2015; @bellonDigitalizationImproveTax2022; @fanDynamicEffectsComputerizing2023]. Sin embargo, ninguno de los trabajos reseñados analiza los efectos de la *recepción*. Esta es una limitación importante, en tanto literatura reciente destaca la importancia de estudiar spillovers al realizar una evaluación completa de cualquier intervención [@lopez-luzuriagaComplianceSpilloversTaxes2019]. En este caso, estudiar la recepción de e-facturas nos aproxima al spillover *downstream* de la política –desde las empresas tratadas hacia sus compradores–. Las políticas de e-facturación generan volúmenes muy importantes de información y los *spillovers* entre empresas pueden ser considerables. Dar una primera aproximación a estos efectos derrame es la principal contribución de mi tesis. Hasta donde tengo conocimiento, este es el primer trabajo en hacer un análisis de este tipo.