# Resultados {#sec-results}

## Caracterización de la recepción de e-facturas {#sec-results-rollout}

En primer lugar, voy a caracterizar la recepción de e-facturas, su evolución y su intensidad. Entender cuanto de las compras de las empresas receptoras de e-facturas queda registrado en e-facturas, da pistas sobre la magnitud de los spillovers que se pueden esperar de la política. 

La emisión de e-facturas comienza con unas pocas empresas de gran porte en 2012. La recepción se extendió rápidamente en el margen extensivo: a fines de 2013 la mitad de las empresas de mi muestra habían recibido al menos una e-factura (@fig-adoption-inSample). En los años que siguieron, el número de empresas emisoras, el número de comprobantes emitidos y el volumen de las operaciones registradas en e-facturas crecieron exponencialmente. Naturalmente, también aumentó el número de empresas receptoras y la proporción de sus compras que quedaban registradas en comprobantes electrónicos.

La @fig-reception-intensity presenta un boxplot del porcentaje del IVA compras declarado por las empresas que quedó registrado en e-facturas, para cada uno de los años desde que se implementó el sistema. Hubo un incremento sostenido de la cobertura en el tiempo: en 2012 las e-facturas registraron 1% del IVA compras de la empresa receptora mediana y en 2016 el 27%. Hay una variación importante entre empresas: en 2016 el rango intercuartílico de la cobertura de IVA compras fue 14%–56%.

La evolución de la recepción de e-facturas no fue homogénea entre empresas. Las empresas que más facturaban antes de la política reciben e-facturas antes  (@fig-takeup-by, panel (a)).  Los tres quintiles superiores se comportan de forma muy similar: más de 75% de estas empresas habían recibido e-facturas en 2013 y al final del período casi todas lo habían hecho. El primer quintil de facturación –mi muestra de análisis– se comporta de forma muy distinta. Aunque la recepción evoluciona en paralelo a los quintiles de mayor facturación, el nivel es sustancialmente menor. En contraste, la recepción en el margen intensivo no presenta diferencias importantes entre quintiles (@fig-reception-intensity-by, panel (a)). En otras palabras, aunque la recepción se haya extendido de forma heterogénea, la proporción del IVA compras registrado en e-facturas fue similar para todas las empresas receptoras a lo largo de la distribución.

La recepción de e-facturas también se extendió de forma heterogénea entre sectores de actividad. La industria manufacturera y el comercio minorista fueron los sectores en que la recepción se generalizó de forma más rápida y sostenida (@fig-takeup-by, panel (b)). A fines de 2013, 75% de las empresas de estos sectores habían recibido un e-factura y al final de 2016 prácticamente todas las empresas del sector lo habían hecho. En contraste, los sectores en que la recepción se extendió más lentamente fueron los servicios y la agricultura. Por otro lado, la intensidad de la recepción también es moderadamente heterogénea entre sectores de actividad (@fig-reception-intensity-by, panel (b)). El IVA compras del sector de servicios no comerciales tienen una mayor cobertura durante todo el período que los demás sectores: el rango intercuartílico de la cobertura en 2015 era 14%–54%. En el otro extremo, en el sector agrícola y el sector manufacturero el rango intercuartílico de la cobertura en 2015 era 8%–41%.

En conclusión, en la [Sección @sec-hypotheses] planteé que (H1) no esperaba que la e-facturación registrara un alto porcentaje de las compras de las empresas receptoras en el período analizado. En ese momento había un número muy reducido de empresas emitiendo comprobantes, y es razonable que la cobertura de las compras a nivel de cada empresa haya sido reducida. Es interesante, sin embargo, ver la velocidad con la que se extendió la recepción en el margen extensivo. Parecería que los primeros emisores de e-facturas, además de tener elevados niveles de facturación, eran proveedores de una proporción sustancial de empresas en la economía uruguaya.

## Impacto sobre el cumplimiento tributario {#sec-results-effect}

Para estudiar el impacto de la recepción de e-facturas sobre el cumplimiento tributario de las empresas, sigo la metodología planteada en la [Sección @sec-method]. Exploto la variación en las fecha de recepción de la primera e-factura con una estrategia de diferencias en diferencias para cuantificar impactos de la recepción sobre IVA compras, IVA ventas e IVA adeudado.

Las variables de interés presentan niveles promedio diferentes entre las cohortes de tratamiento (@fig-time-trends). Las primeras empresas en recibir e-facturas declaran más ventas, más compras y deben más IVA en términos absolutos. Esto no supone un problema para el método de estimación seleccionado, en tanto el supuesto principal es el de tendencias paralelas: en este caso, que los resultados de las empresas que recibieron su primer e-factura en años distintos habrían evolucionado en paralelo luego de recibirla. Una inspección visual de la @fig-time-trends revela que, en promedio, los resultados de las cohortes evolucionan de forma paralela exceptuando al grupo de empresas que no había recibido ninguna e-factura en el período de análisis. Se trata de un grupo de empresas que registran cada vez menos actividad con el correr de los años y presentan tendencias divergentes al resto de las cohortes en todas las variables analizadas.

Para formalizar la inspección visual, grafico los coeficientes del estudio de eventos de la @eq-es en la @fig-twfe-es, estimando una regresión por variable de resultado. Cada uno de los coeficientes graficados corresponde al efecto de tratamiento promedio $l$ períodos después de iniciado el tratamiento, para todas las empresas que recibieron e-facturas por al menos $l$ períodos. Los coeficientes están normalizados al evento $l=-1$ y los intervalos de confianza son del 95%. Ninguno de los coeficientes pre-tratamiento resulta significativo. Aunque esto no valida el supuesto de identificación, si aporta evidencia que apoya el diseño seleccionado. Por otra parte, los coeficientes post-tratamiento oscilan de forma ruidosa alrededor de cero, sin una dinámica claramente distinguible.

Los resultados principales del análisis se presentan en la @tbl-twfe-all. Las columnas 1, 4 y 7 muestran las estimaciones del impacto de empezar a recibir e-facturas con la especificación preferida: panel balanceado de empresas con las variables de resultado censuradas en el percentil 99. Encuentro estimaciones puntuales positivas para todas las variables de resultado, pero son estadísticamente indistinguibles de cero. El efecto sobre el IVA compras es de `0.074` (EE = `0.061`), sobre IVA ventas es de `0.044` (EE = `0.049`) y sobre el IVA adeudado es de `0.093` (EE = `0.089`). 

En la [Sección @sec-hypotheses] planteé que esperaba que la recepción de e-facturas tuviera (H2) un efecto negativo en el IVA compras, (H3) ausencia de efecto en el IVA ventas, y (H4) un efecto positivo sobre el IVA adeudado. Mis resultados no me permiten confirmar ni rechazar las hipótesis. A pesar de que las estimaciones puntuales sean positivas, al no ser estadísticamente distinguibles de cero no puedo afirmar nada acerca de su magnitud ni de su signo.

En la @tbl-twfe-ext testeo explícitamente los cambios en el margen extensivo dicotomizando las variables dependientes. Encuentro que empezar a recibir e-facturas se asocia a un aumento de `1.6%` en la probabilidad de declarar de IVA compras y un aumento de `1.2%` en la de declarar IVA ventas, ambos significativos al 1%. No encuentro efectos sobre la probabilidad de deber IVA. Los resultados sugieren que la recepción de e-facturas llevó a algunas empresas en el márgen a hacer declaraciones más completas de su actividad a la DGI, aún en esta instancia preliminar de implementación. El efecto positivo en el margen extensivo del reporte de IVA compras va en línea con el efecto esperado planteado en (H2a).

Por otra parte, el efecto en el margen extensivo del reporte de IVA ventas cuestiona (H3) la ausencia de efecto en las ventas reportadas. Si bien no puedo descartar que el efecto total sobre las ventas sea nulo, el resultado sugiere que recibir e-facturas puede impactar en la declaración de rubros sobre los que la política en sí no aporta información nueva.

En la hipótesis (H2b) planteaba que el efecto de recibir e-facturas en el márgen intensivo de las compras reportadas iba a ser negativo y, además, iba a dominar el efecto positivo en el margen extensivo. Para testear esta hipótesis, tendría que reestimar considerando únicamente a las empresas que reportan compras positivas. Sin embargo, como adelanté en la [Sección @sec-hypotheses], los datos no me permiten testear este efecto. Si tomo el panel no balanceado de empresas que reportan compras positivas, mi diseño captura efectos de composición importantes que dificultan la interpretación de los coeficientes. Si tomo el panel balanceado, conservo muy pocas observaciones, lo cual pone en cuestión la validez externa del análisis. En consecuencia, no puedo testear la hipótesis (H2b) de forma creíble con el diseño seleccionado y los datos disponibles.

En la siguiente subsección planteo varios ejercicios de robustez para confirmar los resultados de las estimaciones principales y de las estimaciones de efectos en el margen extensivo.

### Robustez {#sec-results-effect-robust}

**Outliers y mediano plazo.** Como primer ejercicio de robustez, reestimo todo censurando las variables de resultado en el percentil 95 (@tbl-twfe-all, columnas 2, 5 y 8). Al aplicar una censura de los resultados más conservadora busco testear la sensibilidad de la estimación a outliers. Segundo, incluyo en la muestra información parcial de 2016 (@tbl-twfe-all, columnas 3, 6 y 9). A pesar de que los datos del año 2016 están incompletos, [^inc16] incluyo estos datos para testear si el efecto agregado difiere en el mediano plazo y a medida la política cobró más fuerza. En ambas especificaciones, los efectos estimados son prácticamente indistinguibles de los hallados con la especificación preferida. 

[^inc16]: En mi muestra, solo cuento con información para un tercio de las empresas en 2016. Balancear la muestra para el período 2009–2015 implicaría conservar un número muy reducido de empresas.

**Margen extensivo.** Como tercer ejercicio de robustez, en la @tbl-twfe-cr23 presento los resultados de la especificación preferida al variar el valor imputado al margen extensivo, siguiendo a @chenLogsZerosProblems2023. En mi estimación preferida asigno al margen extensivo $\varepsilon$ un valor de 10%. En este caso, reestimo con $\varepsilon=$ 0% (columnas 2, 6 y 10), $\varepsilon=$ 20% (columnas 3, 7 y 11) y $\varepsilon=$ 300% (columnas 4, 8 y 12). En ningún caso los efectos estimados se vuelven significativos, pero aumentan en magnitud cuando otorgo más peso al margen extensivo. El hecho de que en ningún caso encuentre un efecto agregado significativo –aún cuando asigno el valor extremo $\varepsilon=$ 300%– sugiere que los efectos en el margen intensivo se sobreponen a los encontrados en el margen intensivo.

**Callaway & Sant'Anna (2021).** En el @sec-appendix-cs21 realizo todas las estimaciones de nuevo aplicando la metodología de @callawayDifferenceinDifferencesMultipleTime2021. Como mencioné en la [Sección @sec-method], este método tiene la ventaja de permitir heterogeneidades arbitrarias en el efecto de tratamiento a lo largo del tiempo y entre cohortes de tratamiento. Con esta estrategia alternativa, aunque cambian los signos de algunas estimaciones, los resultados se mantienen: no encuentro un efecto estadísticamente significativo en ninguno de los resultados analizados.

**Variables instrumentales.** En mi último ejercicio de robustez pruebo una estrategia diferente. Exploto la vinculación entre sectores para computar la probabilidad de que una empresa reciba una e-factura en un determinado año y la utilizo para instrumentar la recepción de e-facturas. Esta metodología tiene la ventaja de permitirme usar todas las empresas del panel. Detallo la estrategia y los resultados en el @sec-appendix-iv. En mi especificación preferida encuentro que un aumento de 10% en el monto de IVA compras registrado en e-facturas lleva a una reducción del 0.3% en el IVA compras declarado por las empresas. No encuentro efectos sobre IVA adeudado e IVA ventas. Los efectos encontrados van en línea con las hipótesis (H2) y (H3), aunque no encuentro efectos en IVA adeudado como planteaba en (H4). La magnitud del efecto sobre IVA compras, sin embargo, es muy reducida, lo cual brinda evidencia adicional a que el efecto pueda ser indetectable con la estrategia principal de diferencias en diferencias.

### Heterogeneidades {#sec-results-effect-het}

En la última parte de mi análisis, exploro posibles efectos heterogéneos de la política, considerando el tamaño de la empresa, la proporción de la producción destinada al consumo final de los hogares y la utilización de insumos importados. La estrategia de estimación sigue la metodología descrita en la @eq-twfe-het.

**Tamaño de la empresa.** La @tbl-twfe-het-size presenta los resultados de estimar la @eq-twfe-het, permitiendo que la política tenga un impacto diferencial de acuerdo al tamaño de la empresa. Como mencioné en la [Sección @sec-hypotheses], este análisis está motivado por estudios recientes que encuentran que el tamaño de una empresa se vincula con su cumplimiento tributario [@klevenWhyCanModern2016; @adhikariSmallBusinessTax2021]. Separo el efecto en dos submuestras de acuerdo a si el nivel de activos promedio de la empresa en 2009–2011 estaba por encima o por debajo del nivel mediano. No hay efectos significativos de la política sobre IVA compras ni IVA ventas, pero sí sobre el IVA adeudado por las empresas de mayor tamaño en la muestra. Sin embargo, la magnitud sugerida de este impacto (30%) debe interpretarse con cautela. La muestra analizada corresponde a las empresas en el primer quintil de facturación, con lo cual la comparación es entre empresas pequeñas y muy pequeñas. No puedo observar que sucede con las empresas grandes con este análisis. Las especificaciones preferidas se presentan en las columnas 1, 4 y 7, pero los ejercicios de robustez en las restantes columnas no alteran sustancialmente los resultados.

**Consumo final de los hogares.** Los mecanismos auto-reforzantes del IVA desaparecen en la etapa del consumo final [@keenVATFraudEvasion2006]. Los sectores de actividad más cercanos a esta etapa tienen mayores posibilidades de evadir, y por ende, de responder de manera más significativa a la política. Para analizar esto, permito que el efecto de la política difiera de acuerdo a la proporción de la producción de cada sector destinada a la producción final. Los sectores de alta exposición son aquellos en que la proporción es superior a la mediana. [^sector-consumption] La @tbl-twfe-het-industry presenta los resultados. No se encuentran efectos significativos en ninguna de las variables de resultado, como se muestra en las columnas 1, 4 y 7, y se confirma con los ejercicios de robustez en las demás columnas.

[^sector-consumption]: Identifico la exposición al consumo final a nivel de sector porque no cuento con esta información a nivel de empresa. Para ello utilizo el Cuadro de Oferta y Utilización del año 2012, computado por el BCU. La @tbl-industry-summary (col. 1) presenta la proporción de la producción final de los sectores destinada al consumo final.

**Importaciones.** Las empresas que importan una mayor proporción de sus insumos tienen una menor probabilidad de ser afectadas por la política, ya que las importaciones no tienen asociada una factura electrónica. Analizo efectos diferenciales de la política de acuerdo a si las empresas pertenecen a un sector cuya proporción de insumos importados es superior a la del sector mediano. [^sector-imports] La @tbl-twfe-het-imports presenta los resultados. Nuevamente, no hay efectos significativos en ninguna de las variables analizadas, en ninguna de las especificaciones testeadas.

[^sector-imports]: Como no puedo identificar cuantas importaciones realiza cada empresa, recurro nuevamente a la identificación por sectores. La @tbl-industry-summary (col. 2) presenta la proporción de los insumos de cada sector que es importada.
